### ISSUE TITLE
Python 3 uses abi tagged dylibs

### ISSUE THREAD

**Issue by anthrotype** [getsentry/milksnake#6] opened 2017-11-25 20:20 UTC
I noticed that, when using milksnake under python3 (tested with both 3.6.3 on Linux and Windows), the fake/empty extension module that is built to trick distutils/setuptools to generate a binary wheel is still present in the generated wheel package along with the shared library built with the external build tool (e.g. cargo).

When running on python2.7, only the shared lib is present.

Is this normal or intended behaviour?
I thought this empty extension module is only a temporary file that is not needed in the final distribution package. In fact, I can delete the extension module file and I am still able to import the generated cffi module.

**Comment by mitsuhiko** [comment] 2017-12-07 12:33
This is in a way a duplicate of #4

**Comment by anthrotype** [comment] 2017-12-07 12:40
well, not quite, because it also happens on linux...

**Comment by mitsuhiko** [comment] 2017-12-07 12:43
Can you clarify them? The only way in which I see this would be possible is if we get the file wrong and do not overwrite it with the dylib. What's the filename you see on linux for the dylib? I have linux wheels and they only contain my built dylib not an empty dylib.

**Comment by mitsuhiko** [comment] 2017-12-07 12:45
Oh I see. Presumably because on Python 3 things are ABI tagged now so the filenames are something like `_whatever.cpython-36m-x86_64-linux-gnu.so`. We probably need to use that filename then.

**Comment by anthrotype** [comment] 2017-12-07 12:45
you can just try to run bdist_wheel using python 3 (I tried Linux or Windows) and you'll see the dummy cpython extension module is packaged with the wheel.

**Closed as completed** 2017-12-07 13:54 UTC
